apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-bedrock-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::535915401024:role/go-bedrock-app-role
